-- 01: Warehouse och databas. Körs som SYSADMIN (byggaren).
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS flights_wh
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS flights_db;